# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-14 23:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='worktype',
            field=models.CharField(choices=[('Road', 'Road'), ('Buiding', 'Building'), ('Maintenence', 'Maintenence'), ('Cleaning', 'Cleaning')], default='Building', max_length=200),
        ),
    ]
