# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-03-14 18:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0003_userdetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='Road',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('start_lat', models.CharField(max_length=10)),
                ('start_long', models.CharField(max_length=10)),
                ('middle_lat', models.CharField(max_length=10)),
                ('middle_long', models.CharField(max_length=10)),
                ('end_lat', models.CharField(max_length=10)),
                ('end_long', models.CharField(max_length=10)),
                ('path', models.CharField(max_length=100)),
                ('status', models.IntegerField()),
            ],
        ),
    ]
