# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-03 20:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0004_road'),
    ]

    operations = [
        migrations.AlterField(
            model_name='road',
            name='path',
            field=models.TextField(max_length=400000),
        ),
    ]
